# Generated by Django 5.0.4 on 2024-04-21 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='State',
            new_name='state',
        ),
    ]
